### PR TITLE
Staging for version increment automation

### PR DESCRIPTION
**Pull request by prudhvigodithi**
Signed-off-by: pgodithi <pgodithi@amazon.com>

### Description
This is the staging PR for to execute workflows that auto raise the version increment PR's
Example: https://github.com/prudhvigodithi/anomaly-detection/pull/1

### Issues Resolved
Part of: https://github.com/opensearch-project/opensearch-build/issues/1375
From solution: https://github.com/opensearch-project/opensearch-build/issues/1375#issuecomment-1159476686
Related issue: https://github.com/opensearch-project/anomaly-detection/issues/605

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by prudhvigodithi** [comment]
Sample PR
`anomaly-detection main : OpenSearch main`
https://github.com/prudhvigodithi/anomaly-detection/pull/2

**Comment by prudhvigodithi** [comment]
Renaming to task `updateVersion` following https://github.com/opensearch-project/opensearch-plugin-template-java/pull/32.

**Comment by prudhvigodithi** [comment]
Renaming to task `updateVersion` following https://github.com/opensearch-project/opensearch-plugin-template-java/pull/32.

**Comment by amitgalitz** [comment]
@prudhvigodithi does this also handle moving main to 3.0.0-SNAPSHOT for example?

**Comment by prudhvigodithi** [comment]
Hey @amitgalitz , following the [discussion](https://github.com/opensearch-project/opensearch-plugins/issues/142#issuecomment-1185858208), `main` once inclined with Core, the task `updateVersion` is called against the version of the core. Please review the PR when you get a chance.
Thank you

**Comment by bbarani** [comment]
@amitgalitz @sean-zheng-amazon  can you please review this PR soon?

**Comment by amitgalitz** [comment]
Once merged will this autochange AD main to whatever Opensearch main is at? for now 3.0.0-SNAPSHOT?

**Comment by amitgalitz** [comment]
Its not letting me re-run the whitesource check for some reason

**Comment by prudhvigodithi** [comment]
> @prudhvigodithi Once merged will this autochange AD main to whatever Opensearch main is at? for now 3.0.0-SNAPSHOT?

Hey @amitgalitz once PR is merged the gradle project should output the task `updateVersion`, now using this task once the Plugins branches are in align with core, then the [workflow](https://github.com/opensearch-project/opensearch-build/blob/main/.github/workflows/increment-plugin-versions.yml) will call the task `updateVersion` to raise an auto increment version PR.
Thank you

**Comment by amitgalitz** [comment]
> > @prudhvigodithi Once merged will this autochange AD main to whatever Opensearch main is at? for now 3.0.0-SNAPSHOT?
> 
> Hey @amitgalitz once PR is merged the gradle project should output the task `updateVersion`, now using this task once the Plugins branches are in align with core, then the [workflow](https://github.com/opensearch-project/opensearch-build/blob/main/.github/workflows/increment-plugin-versions.yml) will call the task `updateVersion` to raise an auto increment version PR. Thank you

got it, so once this is merged, next step is to make sure we align plugin branches with core?

**Review by amitgalitz — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
> got it, so once this is merged, next step is to make sure we align plugin branches with core?

Right @amitgalitz, then the workflow will be triggered to compare to execute `updateVersion` task, which is part of this PR.

**Comment by amitgalitz** [comment]
@prudhvigodithi have you had whitesource check failures on any of the other repos with this PR?

**Comment by ohltyler** [comment]
> > got it, so once this is merged, next step is to make sure we align plugin branches with core?
> 
> Right @amitgalitz, then the workflow will be triggered to compare to execute `updateVersion` task, which is part of this PR.

@prudhvigodithi I'm concerned with aligning plugin branches with core. The [outlined strategy](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#branching) is to have different branching strategies between plugins and core.

**Comment by prudhvigodithi** [comment]
> > > got it, so once this is merged, next step is to make sure we align plugin branches with core?
> > 
> > 
> > Right @amitgalitz, then the workflow will be triggered to compare to execute `updateVersion` task, which is part of this PR.
> 
> @prudhvigodithi I'm concerned with aligning plugin branches with core. The [outlined strategy](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#branching) is to have different branching strategies between plugins and core.

Hey @ohltyler the document should be updated, https://github.com/opensearch-project/opensearch-plugins/issues/142#issuecomment-1176530894

**Review by ohltyler — APPROVED** [review]
LGTM!

**Comment by ohltyler** [comment]
@prudhvigodithi the backports failed for some branches due to merge conflicts for `build.gradle`. Can you help manually resolve?

**Comment by prudhvigodithi** [comment]
Hey @ohltyler 
For 2.x and 2.1 backports I have fixed the DCO error
https://github.com/opensearch-project/anomaly-detection/pull/621
https://github.com/opensearch-project/anomaly-detection/pull/622
For 1.x series I have raised a new PR https://github.com/opensearch-project/anomaly-detection/pull/624
Please check.
Thank you

**Pull request merged**
