### PR TITLE
 Add Integtest.sh for OpenSearch integtest setups

### PR DESCRIPTION
**Pull request by peterzhuamazon**
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

### Description
Add Integtest.sh for OpenSearch integtest setups
This is a file that can be used as an abstraction for integTests to run.
This is better than what ODFE has in which all plugins runs saved in a single yml.
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by ohltyler — APPROVED** [review]

**Comment by kaituo** [comment]
How do you expect us to use this script? In CI or in our day-to-day testing?

**Comment by ohltyler** [comment]
> How do you expect us to use this script? In CI or in our day-to-day testing?

This will be used by infra for running the integ tests during release cycles.

**Review by kaituo — APPROVED** [review]

**Review by ylwu-amzn — APPROVED** [review]

**Comment by ohltyler** [comment]
From @peterzhuamazon, he will handle merging once all plugins' PRs have been approved.

**Comment by peterzhuamazon** [comment]
Please do not merge this I will merged once all the PRs are up.

**Pull request merged**
