### PR TITLE
[Feature/extensions] Add getSettings support for AD

### PR DESCRIPTION
**Pull request by dbwiddis**
### Description
Copies the `getSettings()` method impelmentation from `AnomalyDetectorPlugin` to `AnomalyDetectorExtension`.  This is the third and final step to complete work already done in [SDK #147](https://github.com/opensearch-project/opensearch-sdk-java/pull/147) and and [OS #4519](https://github.com/opensearch-project/OpenSearch/pull/4519) register AD settings with OpenSearch

### Issues Resolved
Fixes [SDK #159](https://github.com/opensearch-project/opensearch-sdk-java/issues/159)
Relates to [SDK #132](https://github.com/opensearch-project/opensearch-sdk-java/issues/132)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by saratvemulapalli — APPROVED** [review]

**Review by owaiskazi19 — APPROVED** [review]

**Comment by dbwiddis** [comment]
> @dbwiddis build is failing

Failure is not associated with this PR.  Looks like package change/rename associated with ExtensionRestResponse from a previous PR merged to the SDK (and probably will change with my consumed param PRs under review).   How often does this project sync with those changes?

**Comment by dbwiddis** [comment]
Updated the RestCreateDetectorAction (which was just a copy of hello world) with the new version of Hello World.  Tests should pass once both 4705 and 169 are merged.

**Comment by dbwiddis** [comment]
169 and 4705 merged, should be able to re-run the tests now.

**Comment by owaiskazi19** [comment]
@saratvemulapalli can you take of it? I don't have access to rerun the test for AD.

**Comment by saratvemulapalli** [comment]
Kicked them off. 
Another hacky way to re-run them is to do a force push without any changes. ;)

**Comment by dbwiddis** [comment]
Will probably have to do that.  I think the rerun is not pulling the updated branches.

**Comment by dbwiddis** [comment]
Well now it's failing on something else entirely, probably something commented out that's still being tested.  I give up.

**Comment by dbwiddis** [comment]
All green.

And this, kids, is why you pay attention to those little IDE flags that say you're using deprecated code. :-)

**Comment by dbwiddis** [comment]
Don't merge yet.  Looks like I need to extend `NodeRequest` and not `TransportRequest`.  See #687 and #688

**Comment by dbwiddis** [comment]
OK, ready to merge.  I'm getting confused by this same fix not working on main here, but I'm not sure it's broken (yet) on main here.

**Pull request merged**
