### PR TITLE
Adding support for integration tests with remote cluster.

### PR DESCRIPTION
**Pull request by saratvemulapalli**
Signed-off-by: Sarat Vemulapalli <vemulapallisarat@gmail.com>

### Description
Adding support for running integration tests with remote cluster.

Plugin integration tests depend on `opensearch.testclusters` gradle plugin exported by OpenSearch. Plugins use the same framework to run integration tests against a remote cluster. The problem is it internally downloads the right distribution to setup the test cluster even though it's not used.

Until now that worked since the min artifact is published for every release. 
In order to step up our testing flow as part of the release, we now would like to run integration tests before the artifacts are published to verify the bundle via https://github.com/opensearch-project/opensearch-build#integration-tests. But since the artifact is not published the tests would see:

Before:
```
* What went wrong:
Execution failed for task ':integTest'.
> Could not resolve all files for configuration ':opensearch_distro_extracted_testclusters--integTest-0-1.1.0-'.
   > Could not resolve opensearch-distribution:opensearch:1.1.0.
     Required by:
         project :
      > Could not resolve opensearch-distribution:opensearch:1.1.0.
         > Could not get resource 'https://artifacts.opensearch.org/releases/core/opensearch/1.1.0/opensearch-min-1.1.0-linux-x64.tar.gz'.
            > Could not HEAD 'https://artifacts.opensearch.org/releases/core/opensearch/1.1.0/opensearch-min-1.1.0-linux-x64.tar.gz'. Received status code 403 from server: Forbidden
      > Could not resolve opensearch-distribution:opensearch:1.1.0.
         > Could not get resource 'https://artifacts.opensearch.org/release-candidates/core/opensearch/1.1.0/opensearch-min-1.1.0-linux-x64.tar.gz'.
            > Could not HEAD 'https://artifacts.opensearch.org/release-candidates/core/opensearch/1.1.0/opensearch-min-1.1.0-linux-x64.tar.gz'. Received status code 403 from server: Forbidden
```
After:
```
% ./gradlew integTestRemote -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername="docker-cluster" -Dhttps=true -Duser=admin -Dpassword=admin
82 tests completed, 12 failed, 1 skipped
```

So this PR adds support to run integration tests for remote clusters without the min artifacts being published at `artifacts.opensearch.org`. 

### Issues Resolved
https://github.com/opensearch-project/OpenSearch/issues/1240
https://github.com/opensearch-project/opensearch-plugins/issues/101
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ohltyler** [comment]
@saratvemulapalli is it reasonable for this to be skipped for 1.2 specifically? Only concern is backporting to 1.2 branch can delay the bundle builds more.

**Comment by saratvemulapalli** [comment]
@ohltyler how much of an effort/time is it to run the builds again? 
This will help avoid running manual tests for the release for the plugin owners.
cc: @peternied @peterzhuamazon

**Comment by ohltyler** [comment]
@saratvemulapalli considering we already have bug fixes backported to 1.2 today, we can add this as well if it gets merged today. Changes make sense to me.

**Review by ohltyler — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
> @ohltyler how much of an effort/time is it to run the builds again? This will help avoid running manual tests for the release for the plugin owners. cc: @peternied @peterzhuamazon

Build is automatic every 2 hours for around 20+10 = 30min for tar + docker.
So I think I agree with @ohltyler to approve and merge.

Thanks.

**Review by peternied — APPROVED** [review]

**Pull request merged**
