### PR TITLE
AD model performance benchmark

### LINKED ISSUE #712: [BUG] Security enabled tests are failing on main branch
**What is the bug?**
All security enabled tests are failling in our current CI: https://github.com/opensearch-project/anomaly-detection/actions/runs/3348855024/jobs/5548340002

**How can one reproduce the bug?**
Follow the steps in this [workflow](https://github.com/opensearch-project/anomaly-detection/pull/710/files#diff-b19025fb2b6fa86c19a171b6e04a71bc04b26344358d2bd72288ea5106bef202R1)

In shorthand run docker from opensearchstaging:3.0.0 and run this command: `./gradlew integTest -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername="docker-cluster" -Dhttps=true -Duser=admin -Dpassword=admin`

**What is the expected behavior?**
All tests pass
**What is your host/environment?**
 - OS: Linux
 - Version OS 3.0.0
 - Plugins AD and Security

**Do you have any additional context?**

Seems like the issue happens on all integ tests when security is enabled. We are getting unauthorized responses on our requests. This might be a breaking change either in security or OS core, meaning the way we send requests is out of date and needs to be changed. Will continue investigating and updating this issue as this might be faced by other plugins.
```
org.opensearch.ad.rest.SecureADRestIT > testGetApiFilterByEnabled FAILED
    org.opensearch.client.ResponseException: method [PUT], host [https://localhost:9200], URI [/_opendistro/_security/api/roles/index_all_access], status line [HTTP/2.0 401 Unauthorized]
    Unauthorized
        at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:384)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:354)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:329)
        at app//org.opensearch.ad.TestHelpers.makeRequest(TestHelpers.java:213)
        at app//org.opensearch.ad.TestHelpers.makeRequest(TestHelpers.java:186)
        at app//org.opensearch.ad.AnomalyDetectorRestTestCase.createIndexRole(AnomalyDetectorRestTestCase.java:447)
        at app//org.opensearch.ad.rest.SecureADRestIT.setupSecureTests(SecureADRestIT.java:62)

    java.lang.NullPointerException
        at org.opensearch.ad.rest.SecureADRestIT.deleteUserSetup(SecureADRestIT.java:112)
        
```

### PR DESCRIPTION
**Pull request by kaituo**
### Description
This PR adds an AD model performance benchmark so that we can compare model performance across versions.

For the single stream detector, we refactored tests in DetectionResultEvalutationIT and moved it to SingleStreamModelPerfIT.

For the HCAD detector, we randomly generated synthetic data with known anomalies inserted throughout the signal. In particular, these are one/two/four dimensional data where each dimension is a noisy cosine wave. Anomalies are inserted into one dimension with 0.003 probability. Anomalies across each dimension can be independent or dependent. We have approximately 5000 observations per data set. The data set is generated using the same random seed so the result is comparable across versions.

We also fixed #712 by revising the client setup code.

Testing done:
* added unit tests to run the benchmark.
* tested security enabled integ tests pass.

Signed-off-by: Kaituo Li <kaituo@amazon.com>

### Issues Resolved
https://github.com/opensearch-project/anomaly-detection/issues/712

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by kaituo** [comment]
gradle build failed due to 

Could not determine the dependencies of task ':integTest'.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> Can't get https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/3.0.0/latest/linux/x64/tar/builds/opensearch/plugins/opensearch-job-scheduler-3.0.0.0.zip to D:\a\anomaly-detection\anomaly-detection\src\test\resources\job-scheduler\opensearch-job-scheduler-3.0.0.0.zip

Known issue: https://github.com/opensearch-project/anomaly-detection/issues/713

**Comment by kaituo** [comment]
Local run of the following commands succeeded:

```
./gradlew build
./gradlew ':test' --tests "org.opensearch.ad.ml.HCADModelPerfTests" -Dtests.seed=2AEBDBBAE75AC5E0 -Dtests.security.manager=false -Dtests.locale=es-CU -Dtests.timezone=Chile/EasterIsland -Dtest.logs=true -Dmodel-benchmark=true
          ./gradlew integTest --tests "org.opensearch.ad.e2e.SingleStreamModelPerfIT" -Dtests.seed=60CDDB34427ACD0C -Dtests.security.manager=false -Dtests.locale=kab-DZ -Dtests.timezone=Asia/Hebron -Dtest.logs=true -Dmodel-benchmark=true
            ./gradlew integTest -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername="docker-cluster" -Dhttps=true -Duser=admin -Dpassword=admin
```

**Comment by ohltyler** [comment]
Based on [this comment](https://github.com/opensearch-project/anomaly-detection/pull/722#discussion_r1025832276), will wait for a commit to update some of the readability of the tests.

Also, I will be ok to merge even with CI failures (including benchmark tests) due to current instability of 3.0 overall. @kaituo if you're able to run a passing result locally and paste the output here that would be great

**Comment by kaituo** [comment]
@amitgalitz re https://github.com/opensearch-project/anomaly-detection/pull/729#discussion_r1025837023

Tried to inherit jackson from core, got the following errors in gradle build:

```
=== Standard error of node `node{::integTest-0}` ===
»   ↓ last 40 non error or warning messages from /local/home/kaituo/code/github/opensearch-ad/build/testclusters/integTest-0/logs/opensearch.stderr.log ↓
» fatal error in thread [main], exiting
»  java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper
»       at com.amazon.randomcutforest.serialize.json.v1.V1JsonToV3StateConverter.<init>(V1JsonToV3StateConverter.java:43)
»       at org.opensearch.ad.AnomalyDetectorPlugin.createComponents(AnomalyDetectorPlugin.java:372)
»       at org.opensearch.node.Node.lambda$new$16(Node.java:715)
»       at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
»       at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
»       at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
»       at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
»       at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
»       at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
»       at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
»       at org.opensearch.node.Node.<init>(Node.java:729)
»       at org.opensearch.node.Node.<init>(Node.java:351)
»       at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242)
»       at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242)
»       at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404)
»       at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180)
»       at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171)
»       at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
»       at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
»       at org.opensearch.cli.Command.main(Command.java:101)
»       at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137)
»       at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103)
»  Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ObjectMapper
»       at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
»       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
»       at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:855)
»       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
»       ... 22 more
```

My changes:

```
diff --git a/build.gradle b/build.gradle
index cf08bf7d..f1f6edee 100644
--- a/build.gradle
+++ b/build.gradle
@@ -139,7 +139,7 @@ configurations.all {
     if (it.state != Configuration.State.UNRESOLVED) return
     resolutionStrategy {
         force "joda-time:joda-time:${versions.joda}"
-        force "com.fasterxml.jackson.core:jackson-core:2.14.0"
+        //force "com.fasterxml.jackson.core:jackson-core:2.14.0"
@@ -676,9 +677,9 @@ dependencies {
     implementation 'software.amazon.randomcutforest:randomcutfores-core:3.0-rc3'

     // force Jackson version to avoid version conflict issue
-    implementation "com.fasterxml.jackson.core:jackson-core:2.14.0"
+    /*implementation "com.fasterxml.jackson.core:jackson-core:2.140"
     implementation "com.fasterxml.jackson.core:jackson-databind:2.4.0"
-    implementation "com.fasterxml.jackson.core:jackson-annotations2.14.0"
2.14.0"*/

     // used for serializing/deserializing rcf models.
 version: '1.8.0'
```

**Review by ohltyler — APPROVED** [review]

**Comment by kaituo** [comment]
> > @amitgalitz re [#729 (comment)](https://github.com/opensearch-project/anomaly-detection/pull/729#discussion_r1025837023)
> > Tried to inherit jackson from core, got the following errors in gradle build:
> 
> interesting it seems like when viewing the dependency list we inherit during our testing on gradle (copied command and output below), databind isn't there but only jackson-core and dataformat is. I had success removing `force "com.fasterxml.jackson.core:jackson-core:2.14.0"` and `implementation "com.fasterxml.jackson.core:jackson-core:2.14.0"`.
> 
> keeping: `implementation "com.fasterxml.jackson.core:jackson-databind:2.14.0" implementation "com.fasterxml.jackson.core:jackson-annotations:2.14.0"`
> 
> Since we still have too keep two dependencies, I don't have a strong preference if we want to remove the force on jackson-core and our explicit dependency for it since we will probably have to continue updating jackson-databind and annotations.
> 
> ```
> ./gradlew dependencies
> compileClasspath - Compile classpath for source set 'main'.
> +--- org.opensearch:opensearch:3.0.0-SNAPSHOT
> |    +--- org.opensearch:opensearch-core:3.0.0-SNAPSHOT
> |    +--- org.opensearch:opensearch-secure-sm:3.0.0-SNAPSHOT
> |    +--- org.opensearch:opensearch-x-content:3.0.0-SNAPSHOT
> |    |    +--- org.opensearch:opensearch-core:3.0.0-SNAPSHOT
> |    |    +--- org.yaml:snakeyaml:1.32
> |    |    +--- com.fasterxml.jackson.core:jackson-core:2.14.0
> |    |    +--- com.fasterxml.jackson.dataformat:jackson-dataformat-smile:2.14.0
> |    |    +--- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.14.0
> |    |    \--- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.14.0
> |    +--- org.opensearch:opensearch-geo:3.0.0-SNAPSHOT
> |    +--- org.apache.lucene:lucene-core:9.5.0-snapshot-a4ef70f
> |    +--- org.apache.lucene:lucene-analysis-common:9.5.0-snapshot-a4ef70f
> |    +--- org.apache.lucene:lucene-backward-codecs:9.5.0-snapshot-a4ef70f
> |    +--- org.apache.lucene:lucene-grouping:9.5.0-snapshot-a4ef70f
> |    +--- org.apache.lucene:lucene-highlighter:9.5.0-snapshot-a4ef70f
> |    +--- org.apache.lucene:lucene-join:9.5.0-snapshot-a4ef70f
> |    +--- org.apache.lucene:lucene-memory:9.5.0-snapshot-a4ef70f
> |    +--- org.apache.lucene:lucene-misc:9.5.0-snapshot-a4ef70f
> |    +--- org.apache.lucene:lucene-queries:9.5.0-snapshot-a4ef70f
> |    +--- org.apache.lucene:lucene-queryparser:9.5.0-snapshot-a4ef70f
> |    +--- org.apache.lucene:lucene-sandbox:9.5.0-snapshot-a4ef70f
> |    +--- org.apache.lucene:lucene-spatial-extras:9.5.0-snapshot-a4ef70f
> |    +--- org.apache.lucene:lucene-spatial3d:9.5.0-snapshot-a4ef70f
> |    +--- org.apache.lucene:lucene-suggest:9.5.0-snapshot-a4ef70f
> |    +--- org.opensearch:opensearch-cli:3.0.0-SNAPSHOT
> |    |    +--- net.sf.jopt-simple:jopt-simple:5.0.4
> |    |    \--- org.opensearch:opensearch-core:3.0.0-SNAPSHOT
> |    +--- com.carrotsearch:hppc:0.8.1
> |    +--- joda-time:joda-time:2.10.13
> |    +--- com.tdunning:t-digest:3.3
> |    +--- org.hdrhistogram:HdrHistogram:2.1.12
> |    +--- org.apache.logging.log4j:log4j-api:2.17.1
> |    +--- org.apache.logging.log4j:log4j-jul:2.17.1
> |    \--- net.java.dev.jna:jna:5.5.0
> +--- org.locationtech.spatial4j:spatial4j:0.7
> +--- org.locationtech.jts:jts-core:1.15.0
> +--- org.apache.logging.log4j:log4j-api:2.17.1
> +--- org.apache.logging.log4j:log4j-core:2.17.1
> +--- net.java.dev.jna:jna:5.5.0
> +--- org.opensearch.plugin:opensearch-scripting-painless-spi:3.0.0-SNAPSHOT
> |    \--- org.opensearch:opensearch:3.0.0-SNAPSHOT (*)
> +--- org.opensearch:opensearch-job-scheduler-spi:3.0.0.0-SNAPSHOT
> +--- org.opensearch:common-utils:3.0.0.0-SNAPSHOT
> +--- org.opensearch.client:opensearch-rest-client:3.0.0-SNAPSHOT
> |    +--- org.apache.httpcomponents.client5:httpclient5:5.1.3
> |    +--- org.apache.httpcomponents.core5:httpcore5:5.1.4
> |    +--- org.apache.httpcomponents.core5:httpcore5-h2:5.1.4
> |    +--- commons-codec:commons-codec:1.15
> |    +--- commons-logging:commons-logging:1.2
> |    \--- org.slf4j:slf4j-api:1.7.36
> +--- com.google.guava:guava:31.0.1-jre
> +--- com.google.guava:failureaccess:1.0.1
> +--- org.javassist:javassist:3.28.0-GA
> +--- org.apache.commons:commons-math3:3.6.1
> +--- com.google.code.gson:gson:2.8.9
> +--- com.yahoo.datasketches:sketches-core:0.13.4
> +--- com.yahoo.datasketches:memory:0.12.2
> +--- commons-lang:commons-lang:2.6
> +--- org.apache.commons:commons-pool2:2.10.0
> +--- software.amazon.randomcutforest:randomcutforest-serialization:3.0-rc3
> +--- software.amazon.randomcutforest:randomcutforest-parkservices:3.0-rc3
> +--- software.amazon.randomcutforest:randomcutforest-core:3.0-rc3
> +--- com.fasterxml.jackson.core:jackson-annotations:2.14.0
> +--- io.protostuff:protostuff-core:1.8.0
> +--- io.protostuff:protostuff-runtime:1.8.0
> +--- io.protostuff:protostuff-api:1.8.0
> +--- io.protostuff:protostuff-collectionschema:1.8.0
> +--- org.apache.commons:commons-lang3:3.12.0
> +--- org.jacoco:org.jacoco.agent:0.8.5
> \--- org.jacoco:org.jacoco.ant:0.8.5
> ```

Make sense. I removed jackson-core dependencies in build.gradle.

**Comment by kaituo** [comment]
build failed due to the same reason:

 * What went wrong:
Could not determine the dependencies of task ':integTest'.
> Can't get https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/3.0.0/latest/linux/x64/tar/builds/opensearch/plugins/opensearch-job-scheduler-3.0.0.0.zip to /home/runner/work/anomaly-detection/anomaly-detection/src/test/resources/job-scheduler/opensearch-job-scheduler-3.0.0.0.zip

**Review by amitgalitz — APPROVED** [review]

**Review by ohltyler — APPROVED** [review]

**Pull request merged**
