### PR TITLE
Adding external property customDistributionUrl to let developer override default distribution Download url

### LINKED ISSUE #381: Enable developer to override Default Distribution Download Url with custom Url
**Is your feature request related to a problem? Please describe.**
Logic to Override Default Distribution Download Url with custom Url has been completed in OpenSearch repo. We need to do corresponding changes in Anomaly Detection repo to make use of this feature. (OpenSearch issue : [1240](https://github.com/opensearch-project/OpenSearch/issues/1240))

**Describe the solution you'd like**
Add external property  "customDistributionUrl" in build.gradle file, to allow developers to pass custom url from cli.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Rishikesh1159**
Signed-off-by: Rishikesh1159 <rishireddy1159@gmail.com>

### Description
This PR adds external property "customDistributionUrl" which can be used to override default distribution download url
 
### Issues Resolved
#381 
 
### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by ylwu-amzn — APPROVED** [review]

**Comment by ylwu-amzn** [comment]
BTW, will this `customDistributionUrl ` work on 1.3.0? I tried `./gradlew integTest -DcustomDistributionUrl="https://ci.opensearch.org/ci/dbc/bundle-build/1.2.0/1127/linux/x64/dist/opensearch-1.2.0-linux-x64.tar.gz"` , seems the integ cluster is still 1.3.0

**Comment by Rishikesh1159** [comment]
@ylwu-amzn sorry the I had to revert my PR in opensearch repo which actually makes his change possible. So, iI could not get this change done in 1.3 version.

**Comment by Rishikesh1159** [comment]
Few days back I released a new PR in opensearch repo which will make this change work. But I will have to wait until 1.3 release to backport my PR to 1.x branch in opensearch repo. I will update this PR once I backport my changes to 1.x in opensarch repo and then we can use different versions by passing a custom URL from plugins.

**Comment by amitgalitz** [comment]
Hi @Rishikesh1159 could you provide some update on this PR?

**Comment by Rishikesh1159** [comment]
Sorry @amitgalitz @ylwu-amzn for the delay, I forgot about this PR. My change got merged in main and it works with all plugins. We just need to document that this feature is available and how to use it to users, which I did in latest commit. Other than that no changes are necessary in this repo for this feature to work.

**Review by amitgalitz — APPROVED** [review]
Thanks for adding this

**Comment by saratvemulapalli** [comment]
@Rishikesh1159 @amitgalitz whats needed here? Another +1 ?

**Comment by amitgalitz** [comment]
On my end, yes, this is just added documentation for something that was added and I verified in the past it works. If nothing changed on @Rishikesh1159 side then just needs another approval.

**Review by saratvemulapalli — APPROVED** [review]

**Comment by saratvemulapalli** [comment]
@amitgalitz I've approved it. Could you merge them if you are good?

**Pull request merged**
