### PR TITLE
[BACKPORT] [1.x] Backport all changes to 1.x

### PR DESCRIPTION
**Pull request by ohltyler**
### Description

This PR cherry-picks all of the changes from `main` branch to `1.x` branch. This is ok, since we currently have nothing in `main` that shouldn't go in the next `1.x` release (which will be `1.1`). Confirmed that there are no differences between `1.x` and `main` via `git diff`

When merging, will not squash, so that the commit history is retained.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ohltyler** [comment]
Build failed, looks like a flaky test:

```
1004 tests completed, 1 failed, 22 skipped
Tests with failures:
 - org.opensearch.ad.transport.MultiEntityResultTests.testMultipleNode
```


Re-running now

**Review by ylwu-amzn — APPROVED** [review]

**Review by kaituo — APPROVED** [review]

**Comment by kaituo** [comment]
> Build failed, looks like a flaky test:
> 
> ```
> 1004 tests completed, 1 failed, 22 skipped
> Tests with failures:
>  - org.opensearch.ad.transport.MultiEntityResultTests.testMultipleNode
> ```
> 
> Re-running now

Could you point me the failed run? Want to check the errors.

**Comment by ohltyler** [comment]
> > Build failed, looks like a flaky test:
> > ```
> > 1004 tests completed, 1 failed, 22 skipped
> > Tests with failures:
> >  - org.opensearch.ad.transport.MultiEntityResultTests.testMultipleNode
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Re-running now
> 
> Could you point me the failed run? Want to check the errors.

Sure: https://github.com/opensearch-project/anomaly-detection/pull/196/checks?check_run_id=3487905317

**Comment by kaituo** [comment]
@ohltyler will create a PR to fix

**Pull request merged**
