### PR TITLE
Fix main build - update import of Releasable and remove reference to BaseExceptionsHelper

### PR DESCRIPTION
**Pull request by cwperks**
There are multiple build issues on main that have been fixed or are being fixed on the extensions branch. This PR is to make those changes in main.

Incorporates changes from:

- https://github.com/opensearch-project/anomaly-detection/pull/928
- https://github.com/opensearch-project/anomaly-detection/pull/929

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by owaiskazi19 — APPROVED** [review]
Except the build failing. Rest LGTM

**Comment by kaituo** [comment]
@cwperks Is the build failing due to outdated nightly-build?

**Comment by cwperks** [comment]
>  java.lang.NoClassDefFoundError: org/opensearch/core/common/io/stream/BaseStreamOutput

I'm getting this locally when running tests too. Looking into this now.

**Comment by cwperks** [comment]
I think the build errors will autoresolve after artifacts are available with this change included: https://github.com/opensearch-project/OpenSearch/pull/8035

**Review by kaituo — APPROVED** [review]

**Pull request merged**
