### PR TITLE
Add utf-8 encoding settings in gradle settings

### LINKED ISSUE #244: [BUG] Several files are using utf-8 encoding, should use ACSII
**Describe the bug**
https://github.com/opensearch-project/opensearch-build/issues/635#issuecomment-929706299

These files cause build failure due to encoding not in ASCII:
```
src/main/java/org/opensearch/ad/caching/CacheBuffer.java: UTF-8 Unicode text
src/main/java/org/opensearch/ad/caching/PriorityCache.java: UTF-8 Unicode text
src/main/java/org/opensearch/ad/caching/PriorityTracker.java: UTF-8 Unicode text
src/main/java/org/opensearch/ad/model/Entity.java: UTF-8 Unicode text
src/main/java/org/opensearch/ad/ratelimit/ColdEntityWorker.java: UTF-8 Unicode text
src/main/java/org/opensearch/ad/ratelimit/RateLimitedRequestWorker.java: UTF-8 Unicode text
src/main/java/org/opensearch/ad/model/ADTaskState.java: Java source, UTF-8 Unicode text
src/main/java/org/opensearch/ad/model/InitProgressProfile.java: Java source, UTF-8 Unicode text
```

```
/tmp/tmpbcap9s69/anomaly-detection/src/main/java/org/opensearch/ad/caching/CacheBuffer.java:54: error: unmappable character (0x80) for encoding US-ASCII
 * We use a layered cache to manage active entities??? states.  We have a two-level
                                                    ^
/tmp/tmpbcap9s69/anomaly-detection/src/main/java/org/opensearch/ad/caching/CacheBuffer.java:54: error: unmappable character (0x99) for encoding US-ASCII
 * We use a layered cache to manage active entities??? states.  We have a two-level
                                                     ^
/tmp/tmpbcap9s69/anomaly-detection/src/main/java/org/opensearch/ad/caching/CacheBuffer.java:56: error: unmappable character (0xE2) for encoding US-ASCII
 * dedicated cache that stores ten (dynamically adjustable) entities??? states per
 * ```

**Other plugins installed**
Please mention if you are using this plugin along side any other plugin. Security for example.

**To Reproduce**
Run the build on Jenkins with `./gradlew assemble --no-daemon --refresh-dependencies -DskipTests=true -Dopensearch.version=1.1.0 -Dbuild.snapshot=false` on CentOS7.
Not producible on local only on Jenkins.

**Expected behavior**
Javadoc build correctly without this unmapping issues.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by peterzhuamazon**
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

### Description
Add utf-8 encoding settings in gradle settings
 
### Issues Resolved
#244 
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by ylwu-amzn — APPROVED** [review]
Approved now to unblock infra team. We need to add back the `'` and `-` later.

**Comment by peternied** [comment]
Could the encoding setting on javadoc grandle task switch to utf-8 so the content can be used as is?

**Comment by peterzhuamazon** [comment]
> Could the encoding setting on javadoc grandle task switch to utf-8 so the content can be used as is?

We can try that as an improvement later.
I have seen some examples here but not yet tested: https://gist.github.com/rponte/d660919434d094bbd35a1aabf7ef1bf0

**Review by ylwu-amzn — APPROVED** [review]

**Review by peternied — COMMENTED** [review]
🚀 Great work!

**Pull request merged**
