### PR TITLE
Increment to 1.3.2

### PR DESCRIPTION
**Pull request by gaiksaya**
### Description
Coming from https://github.com/opensearch-project/opensearch-build/issues/1805 post release activity.
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by amitgalitz** [comment]
lets merge this in first https://github.com/opensearch-project/anomaly-detection/pull/475? @ohltyler @ylwu-amzn, makes sense to merge this into 1.3 and backport to 1.x today? I see that https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.2/latest/linux/x64/builds/opensearch/plugins/opensearch-job-scheduler-1.3.2.0.zip is already ready so that could make 1.3.2 first version bump with no zip upgrade?

**Comment by ohltyler** [comment]
> lets merge this in first #475? @ohltyler @ylwu-amzn, makes sense to merge this into 1.3 and backport to 1.x today? I see that https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.2/latest/linux/x64/builds/opensearch/plugins/opensearch-job-scheduler-1.3.2.0.zip is already ready so that could make 1.3.2 first version bump with no zip upgrade?

Sounds good to me. Assuming you just mean backport #475 to `1.x` and confirm it picks up a 1.4 job-scheduler zip? But I don't see a `1.4` zip available yet, seems there's some infra issues related to that (ref: [ml-commons PR](https://github.com/opensearch-project/ml-commons/pull/256)). URL doesn't resolve either: `https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.4.0/1389/linux/x64/builds/opensearch/plugins/opensearch-job-scheduler-1.4.0.0.zip`

**Comment by ohltyler** [comment]
^ we can have a separate discussion about that in the specific PR though. I'm ok to merge #475 first to 1.3, then @gaiksaya can rebase and remove the manual built zip as part of this PR - or we can handle separately too, either way :)

**Comment by amitgalitz** [comment]
Closing and merging since we made new changes to 1.3 https://github.com/opensearch-project/anomaly-detection/pull/485

**Pull request closed without merging**
