### PR TITLE
Add DCO Check Workflow

### PR DESCRIPTION
**Pull request by amitgalitz**
Signed-off-by: Amit Galitzky amgalitz@amazon.com

### Description
Adding working flow to check whether commits are signed as per DCO.
 
### Issues Resolved
[#256](https://github.com/opensearch-project/anomaly-detection/issues/256)
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by kaituo — DISMISSED** [review]

**Review by ohltyler — DISMISSED** [review]
LGTM - similar to frontend, let's wait for features to merge first before merging this.

**Review by ylwu-amzn — APPROVED** [review]

**Comment by ohltyler** [comment]
@amitgalitz I think it's ok to merge this now

**Comment by amitgalitz** [comment]
> @amitgalitz I think it's ok to merge this now

Sounds good, will just rebase as good practice as its been awhile and merge once approved again

**Review by ohltyler — APPROVED** [review]

**Comment by CEHENKLE** [comment]
Cool...can we close https://github.com/opensearch-project/anomaly-detection/issues/256 ?

**Comment by amitgalitz** [comment]
> Cool...can we close #256 ?

Yes closing it.

**Pull request merged**
