### PR TITLE
[Feature/extensions] Fish out Create Detector and remove everything else for extensions.

### PR DESCRIPTION
**Pull request by saratvemulapalli**
### Description
Commenting out code for all features of AD except create detector.

I've manually tested and create detector still works.

#### Manual Test

1. Create Index
```
curl -XPUT localhost:9200/server_log --data '{
"mappings" : {
    "_default_":{
        "_timestamp" : {
            "enabled" : true,
            "store" : true
        }
    }
  }
}' -H "Content-Type:application/json"
```

2. Ingest a doc
```
curl -XPUT "localhost:9200/server_log/_doc/1?pretty" --data '{"date": "2015-01-01"}' -H "Content-Type:application/json"
{
  "_index" : "server_log",
  "_id" : "1",
  "_version" : 1,
  "result" : "created",
  "_shards" : {
    "total" : 2,
    "successful" : 1,
    "failed" : 0
  },
  "_seq_no" : 0,
  "_primary_term" : 1
}
```

3. Create Detector
```
curl -XPOST "localhost:9200/_plugins/_anomaly_detection/detectors?pretty" -H "Content-Type:application/json" --data '{
"name":"test-detector", "time_field":"date", "indices": [ "server_log*" ]
}'
{
  "_id" : "XinDW4IBUCK3JmVb3oQ0",
  "_version" : 1,
  "_seq_no" : 0,
  "anomaly_detector" : {
    "name" : "test-detector",
    "description" : "",
    "time_field" : "date",
    "indices" : [
      "server_log*"
    ],
    "filter_query" : {
      "match_all" : {
        "boost" : 1.0
      }
    },
    "detection_interval" : {
      "period" : {
        "interval" : 10,
        "unit" : "Minutes"
      }
    },
    "window_delay" : {
      "period" : {
        "interval" : 0,
        "unit" : "Seconds"
      }
    },
    "shingle_size" : 8,
    "schema_version" : 0,
    "feature_attributes" : [ ],
    "last_update_time" : 1659396939315,
    "detector_type" : "SINGLE_ENTITY"
  },
  "_primary_term" : 1
}
```

~**Note** I'll mark the PR in draft state to comment out the tests. Obviously a lot of tests would fail :)~
Everything works!!

### Issues Resolved
Closes https://github.com/opensearch-project/opensearch-sdk/issues/20

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dbwiddis — APPROVED** [review]
LGTM although it's hard to review a negative diff.  Makes me wonder if we shouldn't just start with a fresh repo and bring things over that we want to keep.

**Comment by saratvemulapalli** [comment]
Looking for one more pair of eyes. 
@owaiskazi19 @joshpalis @ryanbogan if you guys have some bandwidth.

**Comment by owaiskazi19** [comment]
> LGTM although it's hard to review a negative diff. Makes me wonder if we shouldn't just start with a fresh repo and bring things over that we want to keep.

+1 on this. @saratvemulapalli WDYT?

**Comment by owaiskazi19** [comment]
Should we merge https://github.com/opensearch-project/anomaly-detection/pull/619 before this?

**Comment by saratvemulapalli** [comment]
@dbwiddis @owaiskazi19 The problem maintain a fresh piece of code is that we have to keep understanding the diff between `main` and `feature/extensions`. 
Its going to be hard to track them, commented code will have everything in place and merging will be easy down the line. 

I would propose keeping this branch with all commented code and when we start integrating the SDK we can pull the fresh pieces of code. What do you guys think?

**Comment by owaiskazi19** [comment]
> @dbwiddis @owaiskazi19 The problem maintain a fresh piece of code is that we have to keep understanding the diff between `main` and `feature/extensions`. Its going to be hard to track them, commented code will have everything in place and merging will be easy down the line.
> 
> I would propose keeping this branch with all commented code and when we start integrating the SDK we can pull the fresh pieces of code. What do you guys think?

Makes sense. Thanks for showing the big picture here.

**Review by owaiskazi19 — APPROVED** [review]
LGTM! Thanks @saratvemulapalli

**Comment by saratvemulapalli** [comment]
> LGTM! Thanks @saratvemulapalli . I don't have the green 😞

Well more commits will earn you the green :)

**Comment by saratvemulapalli** [comment]
> Should we merge #619 before this?

Thats a good point. 
Sure let me review those changes. I'll wait until the PR is merged.

**Pull request merged**
