### PR TITLE
[BACKPORT] [1.x] Update and add documentation files

### PR DESCRIPTION
**Pull request by ohltyler**
Signed-off-by: Tyler Ohlsen <ohltyler@amazon.com>

Backporting #105 to 1.x branch
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ylwu-amzn** [comment]
Seems duplicate effort to send out and review backport PR. Do we have any guideline about backporting?

**Review by ylwu-amzn — APPROVED** [review]

**Comment by ohltyler** [comment]
> Seems duplicate effort to send out and review backport PR. Do we have any guideline about backporting?

Yes, guideline is [here](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#release-branching). The idea is we can always merge things into `main` (even if it's a 2.0 change, etc), and backport changes that should be in the upcoming release (like 1.0, 1.1, etc). This eliminates the need for feature branches as much.

**Comment by ohltyler** [comment]
After `1.0` release, we keep backporting commits to `1.x`, and eventually cut `1.1` from it. Then `1.x` becomes `1.2`, etc.

**Comment by ohltyler** [comment]
@ylwu-amzn I think for backport PRs, 1 approval is sufficient. What do you think?

**Comment by ylwu-amzn** [comment]
> @ylwu-amzn I think for backport PRs, 1 approval is sufficient. What do you think?

Agree, I'm ok with 1 approval.

**Pull request merged**
