### PR TITLE
Update BWC zip links

### PR DESCRIPTION
**Pull request by ohltyler**
Signed-off-by: Tyler Ohlsen <ohltyler@amazon.com>

### Description
Update BWC links to point to OpenSearch 1.1.0, since Open Distro is now officially unsupported. See OpenSearch [maintenance policy](https://opensearch.org/releases.html#maintenance-policy) on supported versions.

This PR also cleans up BWC tests to be compatible with 1.1 as the baseline. Note there was some changes to historical analysis between ODFE 1.13.0.0 (based on ES 7.10.2) => OpenSearch 1.1.0.0.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by kaituo** [comment]
We have similar issue as in https://github.com/opensearch-project/OpenSearch/issues/3001

Might want to try to use 1.0.1 instead of 1.0.0

**Comment by ohltyler** [comment]
> We have similar issue as in [opensearch-project/OpenSearch#3001](https://github.com/opensearch-project/OpenSearch/issues/3001)
> 
> Might want to try to use 1.0.1 instead of 1.0.0

Hmm, seems 1.0.1 is not published: 
```
Could not determine the dependencies of task ':adBwcCluster#fullRestartClusterTask'.
> Can't get https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.0.1/latest/linux/x64/tar/builds/opensearch/plugins/opensearch-anomaly-detection-1.0.1.0.zip to /local/home/ohltyler/workspace/2.2/anomaly-detection-2/src/test/resources/org/opensearch/ad/bwc/anomaly-detection/1.0.1.0/opensearch-anomaly-detection-1.0.1.0.zip
```

**Comment by ohltyler** [comment]
Since there is no components on version 1.0.1.x besides the security patched zip, including OpenSearch / OpenSearch Dashboards, it's inaccessible. Confirming if we should move to 1.1.0, or find a workaround to get the patched security zip.

**Comment by ohltyler** [comment]
This will fail as 1.1 zips are not available at that link yet. Will re-run once the decision to move to 1.1 is finalized and zips are available.

**Comment by ohltyler** [comment]
For some reason historical detector creation is failing for BWC, still investigating:
```
Suite: Test class org.opensearch.ad.bwc.ADBackwardsCompatibilityIT
  2> REPRODUCE WITH: ./gradlew ':adBwcCluster#oldVersionClusterTask1' --tests "org.opensearch.ad.bwc.ADBackwardsCompatibilityIT.testBackwardsCompatibility" -Dtests.seed=6734897D67D83C3A -Dtests.security.manager=false -Dtests.locale=lv -Dtests.timezone=America/Edmonton -Druntime.java=17
  2> java.lang.AssertionError: expected:<1> but was:<0>
        at __randomizedtesting.SeedInfo.seed([6734897D67D83C3A:8C0BB4B31D03E9B0]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:6[47](https://github.com/opensearch-project/anomaly-detection/runs/7663704097?check_suite_focus=true#step:11:48))
        at org.junit.Assert.assertEquals(Assert.java:633)
        at org.opensearch.ad.bwc.ADBackwardsCompatibilityIT.createHistoricalAnomalyDetectorsAndStart(ADBackwardsCompatibilityIT.java:427)
        at org.opensearch.ad.bwc.ADBackwardsCompatibilityIT.testBackwardsCompatibility(ADBackwardsCompatibilityIT.java:156)
```

**Review by amitgalitz — APPROVED** [review]

**Review by kaituo — APPROVED** [review]

**Pull request merged**
