### PR TITLE
WIP: Alias AD index.

### PR DESCRIPTION
**Pull request by dblock**
Signed-off-by: dblock <dblock@amazon.com>

### Description

In progress #40 on indices. 

I am not in love with where this is going. Too much cruft that needs to be refactored so that it's a lot easier to reference an index.
  
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by skkosuri-amzn** [comment]
@dblock To achive zero downtime, this approach looks good. One additional thing we need to manage: plugin indices are configured as [system-indices](https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/system-indices/) In `hybrid` mode these systems must point to legacy indices names, in complete new opensearch install these need to point to new indices names. We can't use alias for this configuration. In new install these are deployed to opensearch.yml from here: https://github.com/opensearch-project/security/blob/main/tools/install_demo_configuration.sh#L376

**Comment by dblock** [comment]
> @dblock To achive zero downtime, this approach looks good. One additional thing we need to manage: plugin indices are configured as [system-indices](https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/system-indices/) In `hybrid` mode these systems must point to legacy indices names, in complete new opensearch install these need to point to new indices names. We can't use alias for this configuration. In new install these are deployed to opensearch.yml from here: https://github.com/opensearch-project/security/blob/main/tools/install_demo_configuration.sh#L376

Are you saying that we cannot use alias for system indices because the alias doesn't follow the same permissions model? Does it not? Or is it something else?

**Comment by skkosuri-amzn** [comment]
> > @dblock To achive zero downtime, this approach looks good. One additional thing we need to manage: plugin indices are configured as [system-indices](https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/system-indices/) In `hybrid` mode these systems must point to legacy indices names, in complete new opensearch install these need to point to new indices names. We can't use alias for this configuration. In new install these are deployed to opensearch.yml from here: https://github.com/opensearch-project/security/blob/main/tools/install_demo_configuration.sh#L376
> 
> Are you saying that we cannot use alias for system indices because the alias doesn't follow the same permissions model? Does it not? Or is it something else?

In hybrid (odfe + opensearch clulster) mode system-indices config must have LEGACY_INDICES and not alias. 
OpenSearch only config must have NEW_INDICES_NAMES. (no alias are created on this mode anyways).

**Comment by dblock** [comment]
Abandoning this approach, closing.

**Pull request closed without merging**
