### PR TITLE
Incremented version to 2.0.1

### PR DESCRIPTION
**Pull request by zelinh**
### Description
Increment version to 2.0.1
Part of https://github.com/opensearch-project/opensearch-build/issues/2165

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by kaituo** [comment]
CI failed with "> Can't get https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.0.1/latest/linux/x64/tar/builds/opensearch/plugins/opensearch-anomaly-detection-2.0.1.0.zip to /home/runner/work/anomaly-detection/anomaly-detection/src/test/resources/org/opensearch/ad/bwc/anomaly-detection/2.0.1.0-SNAPSHOT/opensearch-anomaly-detection-2.0.1.0.zip"

Should be temporary once 2.0.1 zip becomes available.

**Comment by kaituo** [comment]
CI failed with "> Can't get https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.0.1/latest/linux/x64/tar/builds/opensearch/plugins/opensearch-anomaly-detection-2.0.1.0.zip to /home/runner/work/anomaly-detection/anomaly-detection/src/test/resources/org/opensearch/ad/bwc/anomaly-detection/2.0.1.0-SNAPSHOT/opensearch-anomaly-detection-2.0.1.0.zip"

Should be temporary once 2.0.1 zip becomes available.

**Comment by zelinh** [comment]
> CI failed with "> Can't get https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.0.1/latest/linux/x64/tar/builds/opensearch/plugins/opensearch-anomaly-detection-2.0.1.0.zip to /home/runner/work/anomaly-detection/anomaly-detection/src/test/resources/org/opensearch/ad/bwc/anomaly-detection/2.0.1.0-SNAPSHOT/opensearch-anomaly-detection-2.0.1.0.zip"
> 
> Should be temporary once 2.0.1 zip becomes available.

Yes. We would need this to be merged to build the artifacts.

**Comment by amitgalitz** [comment]
> CI failed with "> Can't get https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.0.1/latest/linux/x64/tar/builds/opensearch/plugins/opensearch-anomaly-detection-2.0.1.0.zip to /home/runner/work/anomaly-detection/anomaly-detection/src/test/resources/org/opensearch/ad/bwc/anomaly-detection/2.0.1.0-SNAPSHOT/opensearch-anomaly-detection-2.0.1.0.zip"
> 
> Should be temporary once 2.0.1 zip becomes available.

I agree and it makes sense for now, however doing this for larger releases on multiple plugins could be annoying as some plugins might have actual changes that fail bwc test that are missed and only found later.

**Review by amitgalitz — APPROVED** [review]

**Pull request merged**
