### PR TITLE
Bump version to 1.2.2.

### PR DESCRIPTION
**Pull request by dblock**
Signed-off-by: dblock <dblock@amazon.com>

### Description

Bump version to 1.2.2.

### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by vamshin — APPROVED** [review]
LGTM! Thanks

**Comment by vamshin** [comment]
@dblock workfow seem to fail.

```
| -> Failed installing file:/home/runner/work/anomaly-detection/anomaly-detection/src/test/resources/job-scheduler/opensearch-job-scheduler-1.2.1.0-SNAPSHOT.zip
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
| -> Rolling back file:/home/runner/work/anomaly-detection/anomaly-detection/src/test/resources/job-scheduler/opensearch-job-scheduler-1.2.1.0-SNAPSHOT.zip
Use '--warning-mode all' to show the individual deprecation warnings.
| -> Rolled back file:/home/runner/work/anomaly-detection/anomaly-detection/src/test/resources/job-scheduler/opensearch-job-scheduler-1.2.1.0-SNAPSHOT.zip
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings
| Exception in thread "main" java.lang.IllegalArgumentException: Plugin [opensearch-job-scheduler] was built for OpenSearch version 1.2.1 but version 1.2.2 is running
21 actionable tasks: 12 executed, 9 up-to-date
| 	at org.opensearch.plugins.PluginsService.verifyCompatibility(PluginsService.java:390)
| 	at org.opensearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:803)
| 	at org.opensearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:858)
| 	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:263)
| 	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:237)
| 	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
| 	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
| 	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
| 	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
| 	at org.opensearch.cli.Command.main(Command.java:101)
| 	at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)

FAILURE: Build failed with an exception.
```

**Comment by ohltyler** [comment]
@dblock we also usually replace snapshot job-scheduler zips when version bumping. See #340. I can handle this if you want to close.

**Comment by dblock** [comment]
I see. @ohltyler take it.

**Comment by dblock** [comment]
What's the issue number of getting rid of the checked-in zip? This is quite error prone and you should be able to download the snapshot zip during build.

**Comment by ohltyler** [comment]
Definitely agreed - I'm not familiar with how that was initially set up but agreed it shouldn't need to happen.

**Pull request closed without merging**
