### PR TITLE
[Backport to 1.x] backport multiple PRs

### PR DESCRIPTION
**Pull request by ylwu-amzn**
Signed-off-by: Yaliang Wu <ylwu@amazon.com>

### Description
Backport PRs: #334 , #325, #350, #349 #335, #348,, #353, #339, #354

### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by amitgalitz** [comment]
CI failing cause build-tools 1.2.0-snapshot doesn't seem to be uploaded. I already messaged infra about this and waiting for a response.

**Comment by ylwu-amzn** [comment]
DCO check failed, as this is to backport PRs, should be ok to ignore these
```
  eecc6ece631f2cc2162d620d9cd8a9f1283360d6    Expected "Amit Galitzky <67072393+amitgalitz@users.noreply.github.com>", but got "Amit Galitzky <amgalitz@amazon.com>".
  8ca8dfa31ab83e675fd18aa9fe11c316655b40b0    Expected "Daniel Doubrovkine (dB.) <dblock@dblock.org>", but got "dblock <dblock@dblock.org>".
  b55d9abad0d5e17c66492992ea40bc916e6e5411    Expected "Amit Galitzky <67072393+amitgalitz@users.noreply.github.com>", but got "Amit Galitzky <amgalitz@amazon.com>".
```

**Comment by amitgalitz** [comment]
> DCO check failed, as this is to backport PRs, should be ok to ignore these
> 
> ```
>   eecc6ece631f2cc2162d620d9cd8a9f1283360d6    Expected "Amit Galitzky <67072393+amitgalitz@users.noreply.github.com>", but got "Amit Galitzky <amgalitz@amazon.com>".
>   8ca8dfa31ab83e675fd18aa9fe11c316655b40b0    Expected "Daniel Doubrovkine (dB.) <dblock@dblock.org>", but got "dblock <dblock@dblock.org>".
>   b55d9abad0d5e17c66492992ea40bc916e6e5411    Expected "Amit Galitzky <67072393+amitgalitz@users.noreply.github.com>", but got "Amit Galitzky <amgalitz@amazon.com>".
> ```
I agree, seems okay to still backport PRs, I'm investigating why DCO would fail for these PRs since I had `--signoff` in my commit as I always do and the original PR had no issue.

**Comment by amitgalitz** [comment]
> > DCO check failed, as this is to backport PRs, should be ok to ignore these
> > ```
> >   eecc6ece631f2cc2162d620d9cd8a9f1283360d6    Expected "Amit Galitzky <67072393+amitgalitz@users.noreply.github.com>", but got "Amit Galitzky <amgalitz@amazon.com>".
> >   8ca8dfa31ab83e675fd18aa9fe11c316655b40b0    Expected "Daniel Doubrovkine (dB.) <dblock@dblock.org>", but got "dblock <dblock@dblock.org>".
> >   b55d9abad0d5e17c66492992ea40bc916e6e5411    Expected "Amit Galitzky <67072393+amitgalitz@users.noreply.github.com>", but got "Amit Galitzky <amgalitz@amazon.com>".
> > ```
> 
> I agree, seems okay to still backport PRs, I'm investigating why DCO would fail for these PRs since I had `--signoff` in my commit as I always do and the original PR had no issue.

Seems like this issue is caused by the fact my email was set to private at some point and address changed to `id+username@users.noreply.github.com`, I changed my email to public now. Should be fine from now on but re-running workflow doesn't fix issues for these commits.

**Review by amitgalitz — APPROVED** [review]
LGTM, couldn't find a way to easily roll back sign off check for those commits. Updated my github email to public so it shouldn't fail DCO check the same way again

**Review by ohltyler — APPROVED** [review]

**Pull request merged**
