### PR TITLE
[Release 1.3.5] Add `build.sh`

### PR DESCRIPTION
**Pull request by prudhvigodithi**
### Description
Default `build.sh` in build repo for 1.3.x includes task `publishPluginZipPublicationToZipStagingRepository`.

### Issues Resolved
https://github.com/opensearch-project/opensearch-build/issues/2470

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by ohltyler — APPROVED** [review]

**Review by dblock — CHANGES_REQUESTED** [review]
This should be 1 commit, not 10.

**Comment by Zhangxunmt** [comment]
please squash the 10 commits when merging.

**Review by Zhangxunmt — APPROVED** [review]

**Review by ohltyler — APPROVED** [review]

**Review by ohltyler — APPROVED** [review]

**Comment by dblock** [comment]
Any plans to fix flaky CI? In this PR _none_ of the CI runs succeeded.

**Comment by ohltyler** [comment]
All tests are failing due to some other issue about AD plugin not being installed:
```
org.opensearch.ad.common.exception.EndRunException: AD plugin is disabled. To enable update plugins.anomaly_detection.enabled to true
```

Made a note of it here, looking into it. Something related to 1.3 only

**Pull request merged**
