### PR TITLE
[Backport 1.2] Adding support for integration tests with remote cluster. (#298)

### LINKED ISSUE #315: Update integTest gradle scripts to run via remote cluster independently
**Is your feature request related to a problem?**
With the existing implementation of integration tests, opensearch plugins use the same test framework as local integration tests which spin up test clusters by itself. This is a hacky way to override the endpoint from local spun up test clusters (via `opensearch.testclusters` gradle plugin) with the remote cluster endpoint. 

The solution doesn't work when we would like to test the opensearch bundle as part of the release. The test frameworks expect the artifact to be available before we could test them. To clean this up, plugins have to create gradle scripts for remote endpoints to run https://github.com/opensearch-project/opensearch-build#integration-tests for the release cycle. 

**What solution would you like?**
Refer to: https://github.com/opensearch-project/anomaly-detection/pull/298 and make similar changes to the plugin.
Also if you have a custom name to invoke these tests, update the `integtest.sh` script in https://github.com/opensearch-project/opensearch-build/blob/main/scripts/default/integtest.sh

### PR DESCRIPTION
**Pull request by saratvemulapalli**
Signed-off-by: Sarat Vemulapalli <vemulapallisarat@gmail.com>

### Description
Backport to 1.2: Adding support for integration tests with remote cluster. 
 
### Issues Resolved
opensearch-project/OpenSearch#1240
opensearch-project/opensearch-plugins#101
Closes #315
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by ohltyler — APPROVED** [review]
Thanks! Can you backport to 1.x as well?

**Comment by saratvemulapalli** [comment]
> Thanks! Can you backport to 1.x as well?

Good point. Sure.

**Review by peternied — APPROVED** [review]

**Comment by peternied** [comment]
Just had a quick conversation with @saratvemulapalli offline, when this change goes in we also need an update in the integration test script to invoke the new gradle task otherwise it will fail.

**Review by ylwu-amzn — APPROVED** [review]

**Comment by saratvemulapalli** [comment]
I have no idea why the tests are failing. Not sure if I did a clean merge. 
Will merge changes from origin to my fork and try again.

**Pull request merged**
